### ISSUE TITLE
Не работает переключение в miranda-im

### ISSUE THREAD

**Issue by mkosmach** [kurumpa/dotSwitcher#10]
Переключение также почему-то не отрабатывает в миранде.

Win7 x64
miranda-im x32 v0.10.24 

не работает смена раскладки для только что набранного по Pause

dotSwitcher собирал так
"c:\Windows\Microsoft.NET\Framework\v4.0.30319\MSBuild.exe"
в каталоге с копией на 26.11.2014

**Comment by kurumpa** [comment]
Наверняка то же самое, что и в [этом](https://github.com/kurumpa/dotSwitcher/issues/1) случае. Даже [не знаю пока](http://stackoverflow.com/questions/27720728/cant-send-wm-inputlangchangerequest-to-some-controls), что делать

**Comment by kurumpa** [comment]
Оказалось, что проблемы разного характера.
В миранде аналогично не работает [punto switcher](http://www.kraeg.ru/node/161) и [keyboard ninja](https://ru.wikipedia.org/wiki/Keyboard_Ninja#.D0.98.D0.B7.D0.B2.D0.B5.D1.81.D1.82.D0.BD.D1.8B.D0.B5_.D0.BF.D1.80.D0.BE.D0.B1.D0.BB.D0.B5.D0.BC.D1.8B_.D0.B8_.D0.BE.D0.B3.D1.80.D0.B0.D0.BD.D0.B8.D1.87.D0.B5.D0.BD.D0.B8.D1.8F). Не думаю, что это можно как-то адекватно починить.

**Comment by wizzard0** [comment]
От миранды есть сорцы....

**Comment by mkosmach** [comment]
punto точно работал, пока я его не выкинул, правда на win7 x32
проверю на x64. keyboard ninja не тестил - врать не буду.

**Comment by mkosmach** [comment]
кстати аналогично собранный текущий мастер вообще ничего не делает.
Вернее с наббанным ничего не происходит, просто циклически меняется раскладка при нажатии на Pause: en-ru-en-...

**Comment by mkosmach** [comment]
Беру свои слова назад - все работает теперь и в миранде.
Осталось сделать переключение  раскладки длявыбранного текста.
Большое спасибо.
