### ISSUE TITLE
не работает в IE и Edge windows 10 (10240 лицензия, все апдейты)

### ISSUE THREAD

**Issue by sharp-dev** [kurumpa/dotSwitcher#14]
ни в адресной строке, ни в формах сайтов

так же не работает в приложениях winrt

**Comment by sharp-dev** [comment]
вопрос закрывается с пояснением

все работает в IE, Edge и приложениях winrt windows 10, при условии запуска программы с системного диска, из профиля пользователя или общего профиля

проблема проявляется при запуске с другого дискового устройства, хотя видимых ограничений в правах папки не наблюдается

вероятно это особенности системы контроля прав пользователя, но не самой программы

извините за беспокойство!

**Comment by sharp-dev** [comment]
дополнение - когда программа была запущена с другого диска и не работала в IE, тем не менее она работала в других десктопных программах

по тому собственно и возникло подозрение что это ошибка

**Comment by kurumpa** [comment]
Спасибо. Тут мелькало где-то предположение, что WM_INPUTLANGCHANGE не будет работать в win10, рад, что ложная тревога.
