### ISSUE TITLE
skype 7.12.64.101 под windows 10 x64

### ISSUE THREAD

**Issue by sharp-dev** [kurumpa/dotSwitcher#15]
вчера в скайпе переключение вполне себе замечательно работало, точно версию скайпа не скажу, сегодня приехало обновление до skype 7.12.64.101 - попытка переключения вешает скайп на смерть

на всякий случай перезапускал и skype, и dotSwitcher в разной очередности - это ни как не повлияло

при чем одна из попыток, перед зависанием скайпа, съела последний символ
(в точности как в ранней версии dotSwitcher в cmd)

проблема наблюдается под windows 10 x64 prof, русская, сборка 10240, все апдейты, лицензия
версия skype - 7.12.64.101

**Comment by uafcybs** [comment]
есть такое и у меня. win 10 x64 pro. skype 7.12.80.101

**Comment by kurumpa** [comment]
а если в настройках свитчера поставить задержку 100-200 мс, тоже виснет?

**Comment by sharp-dev** [comment]
проверил - с задержкой 200 мс успешно затирает ввод и все.. виснем, увы
(хотя становится понятен феномен с пропажей одного символа)

**Comment by sharp-dev** [comment]
напомню что перед обновлением скайпа этой проблемы не было, по крайней мере у меня.

не могу назвать предыдущую версию, но она тоже была свежая - где то в пределах одного полутора месяцев тому назад видел предыдущее обновление

**Comment by kurumpa** [comment]
ffffuuuuuu. Исторически скайп не любит WM_INPUTLANGCHANGE, и я даже не знаю, что с этим сделать, если даже магический Sleep() не решает проблему :) специально для скайпа эмулировать win+space? Реверсить пунту?

**Comment by sharp-dev** [comment]
хмм.. ну скажем так - проверить версию операционки не проблема, по сему эмуляцию win+space имеет смысл попробовать в принципе для 10ки, но то что для скайпа... хотя бы для эрудиции..

по моим ощущениям legacy переключения клавиатуры в 8+, или по крайней мере в 10, работаю глючновато

**Comment by sharp-dev** [comment]
если будет пробная версия по этой теме - готов принять участие в тестировании

**Comment by kurumpa** [comment]
я так понял, не существует не-глючноватого способа переключать раскладку в этих ваших окнах :)

**Comment by skyfion** [comment]
поковырял проблему пока решил так 
1) Exit from Skype application.
2) Find Skype.exe in Windows Explorer (In my system it is C:\Program Files (x86)\Skype\Phone\Skype.exe)
3) Right Click, select Properties.
4) Go to Compatibility tab.
5) Select compatibility mode Windows Vista SP2.
6) Start Skype.
7) In menu Tools / Options / Advanced / Connection turned off the option "Enable uPnP" - this solves the issue with hanging Skype on start up in compatibility mode.
 Lauch Control Panel=>Change Input Method=>Advanced settings:
- Select "Use the desktop language bar when it's available"
- In personalization data choose "Don't use automatic learning"
- In web content language check "Don't let websites access my language list"

**Comment by kurumpa** [comment]
@skyfion Воу, серьезное решение :smile:

**Comment by skyfion** [comment]
лучший костыль другого еще никто не предложил (в пунте это решили? последний раз когда пробовал зависал так же)

**Comment by CAXAline** [comment]
@skyfion В пунте решили

**Comment by kurumpa** [comment]
Похоже, назревает дилемма: либо хачить и пожертвовать читабельностью исходников (а они однажды станут читаемыми :)) либо оно будет работать не во всех скайпах. Если честно, я за второй вариант. Может кто поможет реверснуть пунту с решенной этой проблемой? Я видел, что там для разных программ разный алгоритм, но хаки довольно обширные, и я это дело бросил...

**Comment by skyfion** [comment]
т.е. if (skype) { положить ногу через попу наплече и переключить раскладку } if else (word) { еще что-то} ?? ))))

**Comment by sharp-dev** [comment]
а есть наблюдения по поводу свежего скайпа НЕ в10ке? на пример в в 7ке...
о скайпе и 10ке (и вообще...) - как М$ выкупили скайпа... я все больше мечтаю о том дне когда они допилят winrt скайп уже.. в нем меня бесит больше десктопного только одно - орут не в попад о входящих события и десктоп, и смартфон и планшет ... даже если на де ктопе уже пошла беседа...

это такое длинное высказывание на тему - я бы забил на настольный скайп... как минимальный хак - игнорить его... что бы не валить...

**Comment by kurumpa** [comment]
у меня на вин7х64 скайп 7.12.80.101. Длина успешно конвертируемого слова зависит от delay before switching :) 100 мс позволяют переключать 3-4 буквы, 200 мс уже достаточно для не очень больших слов :smile: Скайп тупит с обработкой "нажатий" backspace (точнее там как-то хитро, я не очень понимаю как работают эти хитрые языковые системы ввода), отсюда такое странное поведение. Но не виснет и не падает.

**Comment by skyfion** [comment]
смотрел в пунту 
там два метода переключить раскладку 
1) hook метод 
2) hotkey метод (этот используется для проблемного софта есть даже список) 
     насколько я понял суть 2-ого метода это найти хоткей (смотрит в реестр HKEY_CURRENT_USER, L"Keyboard Layout\\Toggle") каким хоткеем переключается раскладка и тупо эмулирует SendInput
вот и все.

**Comment by kurumpa** [comment]
@skyfion Спасибо. Я попробую послать hotkey вместо WM_INPUTLANGCHANGE в скайп и посмотреть, успеет ли он переключить раскладку :)

**Comment by skyfion** [comment]
@kurumpa удачи, проект хороший уже использую его.

**Comment by sharp-dev** [comment]
еще наблюдение - тот же скайп, тот же билд свитчера (настройки по дефолту), только по server 2008R2 по RDP - не валит, однако и не переключает, видно как весь набор затирается, потом возвращается на место без изменений, язык ввода в системе тоже не меняется

**Comment by skyfion** [comment]
@sharp-dev если верить пунте которого я зареверсил проблема зависания наблюдается только с версии 6.2 а это 2012 сервер или выше.. все что ниже не должно зависать

**Comment by baxtep** [comment]
а дайте пожалуйста последний екзешник? и можно его выкладывать прям на гитхабе? win10 x64

**Comment by kurumpa** [comment]
@baxtep https://drive.google.com/open?id=0Bx04pjF-PrYvVm5aNURnREttZkU вот это пока. но я уже начал немного рефакторить и багофиксить, так что надеюсь, скоро будет еще свежее версия. и да, @skyfion, hotkey в моем скайпе  работает лучше, чем WM_INPUTLANGCHANGE. Думаю теперь, а нужен ли вообще этот глючноватый способ.

**Comment by sharp-dev** [comment]
любопытненько на счет "последнего экзешника" http://i.imgur.com/AbFfWwq.png

**Comment by sharp-dev** [comment]
1 - "закрытие" нажал по ошибке
2 - а вот скрин по поводу вируса в "последнем экзешнике" не ошибка

**Comment by kurumpa** [comment]
печальбеда. После релиза надо будет им отправить на анализ, я с таким уже сталкивался

**Comment by baxtep** [comment]
да. хром не дает скачать и винда удаляет его. отстой.

**Comment by skyfion** [comment]
@kurumpa  .. возможно есть софт где метод hotkey глючит а работает только WM_INPUTLANGCHANGE...) в пунте пошли путем если глючит делаем hotkey

**Comment by sharp-dev** [comment]
сборка в ночь с 22.11.15 на 23.11.15 (по Мск) проблему решает
