### ISSUE TITLE
"Незаметный" режим работы

### ISSUE THREAD

**Issue by dartraiden** [kurumpa/dotSwitcher#3]
Хотелось бы видеть то, что уже года 4 не могут сделать в пунте - нормальную работу "тихого" режима, когда программа висит в процессах, но не маячит в трее. В пунте же после перезапуска/падения Проводника иконка в трее вылезает снова, игнорируя соответствующую настройку. Править это они не хотят ссылаясь на смешную отговорку, что, дескать, это никому не нужно, кроме кулхацкеров, желающих использовать пунту в качестве кейлоггера.

**Comment by kurumpa** [comment]
Теперь дотСвитчер можно использовать в качестве кейлоггера :)
