### ISSUE TITLE
Активно-развивающийся аналог

### ISSUE THREAD

**Issue by iamkarlson** [kurumpa/dotSwitcher#31]
Нашел для себя [SimpleSwitcher](https://github.com/alexazz19/SimpleSwitcher/)
Делает все что нужно, и активно пилится автором. Я понимаю что странно заявлять это здесь, тем более я сам предпринимал попытки пилить что-то в этом проекте, но времени нет, но кому если надо тула работает отлично.

**Comment by BladeMight** [comment]
Ну для меня не очень...
1. Иногда меняет регистр после изменения.
2. Кнопка переключения нескольких слов работает как-то не так(сначала последнее потом предпоследнее и т.д. до первого а потом все вмести и опять по кругу)
3. Плюс насчет административных программ, он написал столько всего... а нужно всего-то создать задание в планировщике.
4. Он на Си++.
Ну раз уж говорим о аналогах то вот мой [Mahou](https://github.com/BladeMight/Mahou), в нем все пофиксено уже давно.

**Comment by Omega9** [comment]
Существует вообще хоть одна легкая программа без всех этих функций исправления текста, набитого не в той раскладке, а просто чтобы переключать раскладку CapsLock'ом? Это единственная реально нужная функция что в PuntoSwitcher, что в dotSwitcher.

**Comment by iamkarlson** [comment]
Я не думаю что это займет много времени чтобы написать такую на .net'е

On Sat, Jun 25, 2016 at 3:29 PM Omega9 <notifications@github.com> wrote:

> Существует вообще хоть одна легкая программа без всех этих функций
> исправления текста, набитого не в той раскладке, а просто чтобы переключать
> раскладку CapsLock'ом? Это единственная реально нужная функция что в
> PuntoSwitcher, что в dotSwitcher.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/kurumpa/dotSwitcher/issues/31#issuecomment-228534396>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AEUwZpua_vQJt5SSBk5Wke-lV7Q39iK4ks5qPREvgaJpZM4I5GOM>
> .
>
-- 
Best regards,
Georgy Grigoryev
Phone +971501602901

**Comment by BladeMight** [comment]
`просто чтобы переключать раскладку CapsLock'ом?.`
Ну, так это ужас как легко...

**Comment by BladeMight** [comment]
Сейчас, добавлю в Mahou.

**Comment by BladeMight** [comment]
[Вот Mahou версия 1.0.0.7](https://github.com/BladeMight/Mahou/releases/tag/v1.0.0.7), в ней добавлена возможность переключать раскладку CapsLock'ом.

**Comment by ivangretsky** [comment]
Попробовал Mahou - всё работает. 

Уважаемый kurumpa! Прошу Вас высказаться, что Вы думаете об этой программе. Ваше мнение для нас важно - мы предпринимали некоторые усилия, в том числе и маркетинговые, для продвижения Вашей освобождающей (хотя бы слегка) от слежки Пунты свитчера программы.

**Comment by BladeMight** [comment]
>Уважаемый kurumpa! Прошу Вас высказаться

[Вот](https://github.com/BladeMight/Mahou/issues/1) что он говорил и [вот](https://github.com/kurumpa/dotSwitcher/tree/dotSwitcherNew(MahouEngine)) что из этого получилось.

Так что движок Mahou по мощнее будет....

**Comment by ivangretsky** [comment]
Подскажите тогда, что Вы предпочтительней: изпользовать dotSwitcher на основе Mahou или просто Mahou. Мне лично кажется, что у имени dotSwitcher больше шансов, но не мне одному судить. Подскажите, как развиваются продукты - параллельно или один заброшен?

**Comment by BladeMight** [comment]
> один заброшен?

Да, **dotSwticher** не обновляется... (тот что на моем движке наверно последний...)

> Подскажите тогда, что Вы предпочтительней: изпользовать dotSwitcher на основе Mahou или просто Mahou.

Просто Mahou, я частенько ее обновляю. (Если найдете ошибки [дайте мне знать](https://github.com/BladeMight/Mahou/issues))

**Comment by Omega9** [comment]
>>просто чтобы переключать раскладку CapsLock'ом?.

>Ну, так это ужас как легко...

К сожалению, это вешает хромобраузеры точно так же, как dotSwitcher.

**Comment by BladeMight** [comment]
> вешает хромобраузеры 

Не у всех, у меня ни разу не вешал, я очень часто хромом пользуюсь.

**Comment by BladeMight** [comment]
@Omega9 А еще в Mahou можно воспользоваться [эмуляцией переключения раскладки](https://github.com/BladeMight/Mahou/wiki/%D0%A1%D0%BF%D0%B8%D1%81%D0%BE%D0%BA-%D1%84%D1%83%D0%BD%D0%BA%D1%86%D0%B8%D0%B9#%D0%AD%D0%BC%D1%83%D0%BB%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D1%82%D1%8C-%D0%BF%D0%B5%D1%80%D0%B5%D0%BA%D0%BB%D1%8E%D1%87%D0%B5%D0%BD%D0%B8%D0%B5-%D1%80%D0%B0%D1%81%D0%BA%D0%BB%D0%B0%D0%B4%D0%BA%D0%B8) и вешаться ничего не будет.

**Comment by iamkarlson** [comment]
пользуюсь махау с тех пор, все работает, проблем не встречал (была одна, но разработчик быстро пофиксил). если не брать в расчет неординарность личности разработчика, сама программа ОК и не вижу смысла держать открытой этот тикет
