### ISSUE TITLE
Возможность изменения клавиш для смены раскладки

### ISSUE THREAD

**Issue by AndreWin** [kurumpa/dotSwitcher#4]
Здравствуйте! У меня на ноутбуке нет клавиши Break. Пожалуйста, добавьте возможность изменить клавиши например на Insert. Заранее спасибо.

**Comment by kurumpa** [comment]
Пока не добился стабильной работы с alt и win, но назначать кнопки, шифт-кнопки и контрол-кнопки теперь можно

**Comment by AndreWin** [comment]
Спасибо!)
