### ISSUE TITLE
Linux support

### ISSUE THREAD

**Issue by metya** [kurumpa/dotSwitcher#41]
Please, can you add Linux support? 

For windows there are several kind of solution, but for linux there is a xneur and it's shit and don't developing anymore.

**Comment by kurumpa** [comment]
Unfortunately I am not good at Linux programming :( I don't know how keyboard layouts work in Linux and MacOS, the latter one is even bigger annoyance for me as I have switched to MacOS and struggle.

**Comment by metya** [comment]
thanks!
