### ISSUE TITLE
It crashes QT-based applications

### ISSUE THREAD

**Issue by Pulkinen** [kurumpa/dotSwitcher#47]
How to reproduce error:
1. Install Anki windows client: https://apps.ankiweb.net/
2. Go to any text input control, write something
3. Press Break key

After that, Anki freezes. Have tested under Windows 10 LTSC

**Comment by Pulkinen** [comment]
Sorry, it is not dotSwitcher problem, it is QT6 issue

**Comment by Pulkinen** [comment]
Sorry, it is not dotSwitcher problem, it is QT6 issue

**Comment by kurumpa** [comment]
Oh, I see. Good to know, thanks.
