### ISSUE TITLE
Add Ukrainian flag

### ISSUE THREAD

**Issue by MOLNIO** [kurumpa/dotSwitcher#48]
Good afternoon. Tell me please, will you be able to add support for the Ukrainian flag to the program?

**Comment by kurumpa** [comment]
Слава Україні ) а де саме має бути флаг?

**Comment by MOLNIO** [comment]
Героям Слава! В системному треї є тільки американський прапор і російський з тих мов що я користуюсь. А українського нема( тільки значок програми замість нього. Якщо буде можливість то додайте наш прапор. Дякую)

**Comment by kurumpa** [comment]
Справа в тому, що я не робив прапорів взагалі (ну тобто я не пам'ятаю) Це віндовз показує прапори, чи моя програма?

**Comment by MOLNIO** [comment]
Я думаю що програма показує. Бо в налаштуваннях на вкладці "основне" є чек бокс "показувати флаги в трее". Російський є американський теж а коли перемикаю на українську розкладку то просто показує логотип програми.

**Comment by kurumpa** [comment]
я подивлюся

**Comment by kurumpa** [comment]
А можете заскріншотити? Я такого точно не робив, може це форк якийсь )

**Comment by kurumpa** [comment]
Може то Mahou від BladeMight, там он у нього є таке https://github.com/BladeMight/Mahou/issues/405

**Comment by MOLNIO** [comment]
Вибачаюсь я походу поплутав програми у вас DotSwitcher а я скачав програму SimpleSwitcher

**Comment by kurumpa** [comment]
Тоді закриваю )
